name: "Use Python Dependencies"

description: "Checks if the dependencies have been cached with the hash of the requirements.txt file."

runs:
  using: "composite"
  steps:
    - name: "🐍 Setup Python"
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: "💾 Cache pip dependencies"
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: "📦 Install"
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: pip install -r requirements.txt
      shell: bash
